version: "3"
services:
  db:
    image: mariadb:latest
    ports:
    - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password

  main-application:
    image: docker-food-order-delivery
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/main?createDatabaseIfNotExist=true
